routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin', function () {
    return view('pages.admin');
});

Route::middleware(['auth'])->group(function () {

  Route::resources([
      'agenda' => 'AgendaController',
      'lembretes' => 'LembretesController',
  ]);

});


// Route::get('/usuarios', function () {
//     return view('pages.usuarios');
// });

// Route::get('/media', 'FirstController@media');
//
// Route::get('/nomes', 'FirstController@nomes');
//
// Route::get('/soma', 'FirstController@soma');
//
// Route::get('/lista', 'FirstController@lista');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Agenda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
 //
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use App\Agenda;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;


class AgendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $entradas = Agenda::all();

        return view('pages.agenda.index', compact('entradas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('pages.agenda.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $rules = array(
        'nome'      => 'required|string|max:255',
        'endereco' => 'required|string|max:255',
        'email'      => 'required|string|max:255',
        'telefone'   => 'required|string|max:255',
      );

      $validator = validator::make(Input::all(), $rules);

      if ($validator->fails()) {
        return Redirect::to('/agenda')
        ->withErrors($validator);
        // dd($validator);
      } else {
        // store
        $entrada = new Agenda;
        $entrada->nome        = Input::get('nome');
        $entrada->endereco    = Input::get('endereco');
        $entrada->email       = Input::get('email');
        $entrada->telefone    = Input::get('telefone');
        $entrada->save();

        // redirect
        Session::flash('message', 'Sucesso!');
        return Redirect::to('/agenda');
      }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $entrada = Agenda::find($id);

      return view('pages.agenda.edit')->with('entrada', $entrada);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $rules = array(
        'nome'      => 'required|string|max:255',
        'endereco' => 'required|string|max:255',
        'email'      => 'required|string|max:255',
        'telefone'   => 'required|string|max:255',
      );

      $validator = validator::make(Input::all(), $rules);

      if ($validator->fails()) {
        return Redirect::to('/agenda')
        ->withErrors($validator);
        // dd($validator);
      } else {
        // store
        $entrada = Agenda::find($id);
        $entrada->nome        = Input::get('nome');
        $entrada->endereco    = Input::get('endereco');
        $entrada->email       = Input::get('email');
        $entrada->telefone    = Input::get('telefone');
        $entrada->save();

        // redirect
        Session::flash('message', 'Sucesso!');
        return Redirect::to('/agenda');
      }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      // delete
      $del = Agenda::find($id);
      $del->delete();

      // redirect
      Session::flash('message', 'Removido com sucesso!');
      return Redirect::to('/agenda');    }
}

resources/views/pages/agenda/create.blade.php
@extends('templates.default')
@section('title')
  Agenda | Nova Entrada
@endsection

@section('content')

  <div class="container">

    <div class="row">
      <div class="col-md-6 col-sm-12">
        <form action="{{ route('agenda.store') }}" method="post">
          {{ csrf_field() }}

          <div class="form-group">
            <label for="exampleFormControlInput1">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome">
          </div>
          <div class="form-group">
            <label for="exampleFormControlInput2">Endereço</label>
            <input type="text" class="form-control" id="endereco" name="endereco">
          </div>
          <div class="form-group">
            <label for="exampleFormControlInput3">E-mail</label>
            <input type="email" class="form-control" id="email" name="email">
          </div>
          <div class="form-group">
            <label for="exampleFormControlInput4">Telefone</label>
            <input type="number" class="form-control" id="telefone" name="telefone">
          </div>

          <input class="btn btn-primary" type="submit" value="Submit">
          <input class="btn btn-warning" type="reset" value="Reset">

        </form>

      </div>
    </div>
  </div>


@endsection

resources/views/pages/agenda/edit.blade.php
@extends('templates.default')
@section('title')
  Agenda | Editar | {{$entrada->id}}
@endsection

@section('content')

  <div class="container">

    <div class="row">
      <div class="col-md-6 col-sm-12">
        <form action="{{ route('agenda.update', $entrada->id) }}" method="post">
          @method('PUT')
          @csrf

          <div class="form-group">
            <label for="exampleFormControlInput1">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" value="{{ $entrada->nome }}">
          </div>
          <div class="form-group">
            <label for="exampleFormControlInput2">Endereço</label>
            <input type="text" class="form-control" id="endereco" name="endereco" value="{{ $entrada->endereco }}">
          </div>
          <div class="form-group">
            <label for="exampleFormControlInput3">E-mail</label>
            <input type="email" class="form-control" id="email" name="email" value="{{ $entrada->email }}">
          </div>
          <div class="form-group">
            <label for="exampleFormControlInput4">Telefone</label>
            <input type="string" class="form-control" id="telefone" name="telefone" value="{{ $entrada->telefone }}">
          </div>

          <input class="btn btn-primary" type="submit" value="Submit">
          <input class="btn btn-warning" type="reset" value="Reset">

        </form>

      </div>
    </div>
  </div>


@endsection

resources/views/pages/agenda/index.blade.php
@extends('templates.default')
@section('title')
  Agenda
@endsection

@section('content')

  <div class="container">
    <div class="row">
      <div class="col-md-10 col-sm-12">
        <table class="table table-bordered table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Nome</th>
              <th scope="col">Endereço</th>
              <th scope="col">E-mail</th>
              <th scope="col">Telefone</th>
              <th scope="col">Ações</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($entradas as $value)
              <tr>
                <td>{{ $value->id }}</td>
                <td>{{ $value->nome }}</td>
                <td>{{ $value->endereco }}</td>
                <td>{{ $value->email }}</td>
                <td>{{ $value->telefone }}</td>
                <td>
                  <div class="btn-group" role="group" aria-label="Basic example">
                    {{-- <a href="#" class="btn btn-primary btn-lg btn-sm disabled" role="button" aria-pressed="true">Mostrar</a> --}}
                    <a href="{{ URL::to('agenda/' . $value->id . '/edit') }}" class="btn btn-info btn-lg btn-sm" role="button" aria-pressed="true">Editar</a>
                    {{-- <a href="" class="btn btn-danger btn-lg btn-sm" role="button" aria-pressed="true">Excluir</a> --}}
                    <form class="" action="{{ URL::to('agenda/' . $value->id) }}" method="post">
                        @method('DELETE')
                        @csrf
                        <input class="btn btn-danger btn-sm" type="submit" value="Excluir">
                    </form>

                  </div>
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
      <div class="col-md-2 col-sm-12">
        <a href="{{ URL::to('agenda/create') }}" class="btn btn-success btn-lg btn-sm" role="button" aria-pressed="true" style="margin-top: 2em;">Nova Entrada</a>
        <a href="{{ URL::to('/') }}" class="btn btn-dark btn-lg btn-sm" role="button" aria-pressed="true" style="margin-top: 2em;">Voltar</a>
      </div>
    </div>
  </div>


@endsection